"""Sanitized demo project generation for DevArch Framework."""

from __future__ import annotations

import csv
import json
from pathlib import Path


DEMO_PROJECT = "demo-archaeology"


def _write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def create_demo_project(root: str | Path = ".", project_name: str = DEMO_PROJECT, force: bool = False) -> Path:
    """Create a small sanitized demo project under projects/<project_name>.

    The demo uses invented commit/session data. It contains no raw private logs,
    no personal telemetry, and no external behavioral exports.
    """
    root = Path(root)
    project_root = root / "projects" / project_name
    if project_root.exists() and not force:
        raise FileExistsError(f"Demo project already exists at {project_root}. Use force=True to overwrite.")

    data_dir = project_root / "data"
    deliverables_dir = project_root / "deliverables"
    data_dir.mkdir(parents=True, exist_ok=True)
    deliverables_dir.mkdir(parents=True, exist_ok=True)

    _write_json(
        project_root / "project.json",
        {
            "name": project_name,
            "description": "Sanitized demo project for Dev-Archaeology",
            "repo_url": "https://github.com/example/demo-archaeology",
            "developer": {"name": "Demo Developer", "github": "demo"},
            "timeline": {"start_date": "2026-01-01", "end_date": "2026-01-05", "total_days": 5},
            "overrides": {"era_count": 3, "total_commits": 6, "active_days": 4},
            "visualization": {
                "title": "DEMO ARCHAEOLOGY",
                "subtitle": "A sanitized sample project",
                "counters": [
                    {"label": "commits", "value": 6},
                    {"label": "eras", "value": 3},
                ],
                "agent_colors": {"Human": "#74c0fc", "Agent": "#51cf66"},
                "era_colors": {"era-01": "#74c0fc", "era-02": "#51cf66", "era-03": "#ffd43b"},
            },
            "data_sources": {"github_api": False},
        },
    )

    commits = [
        ["demo001", "2026-01-01 09:00:00 +0000", "docs: write initial product intent", "Demo Developer"],
        ["demo002", "2026-01-01 11:00:00 +0000", "feat: scaffold prototype", "Agent"],
        ["demo003", "2026-01-02 15:30:00 +0000", "fix: wire prototype output", "Agent"],
        ["demo004", "2026-01-03 10:15:00 +0000", "test: add behavior checks", "Agent"],
        ["demo005", "2026-01-05 13:00:00 +0000", "refactor: extract audit boundary", "Demo Developer"],
        ["demo006", "2026-01-05 16:45:00 +0000", "docs: publish remediation notes", "Demo Developer"],
    ]
    with (data_dir / "github-commits.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["hash", "date", "message", "author"])
        writer.writerows(commits)

    _write_json(
        data_dir / "human-messages.json",
        [
            {"session_id": "demo-session-1", "timestamp": "2026-01-01T09:00:00Z", "messages": "We need a prototype that proves the core loop."},
            {"session_id": "demo-session-2", "timestamp": "2026-01-03T10:00:00Z", "messages": "The audit should catch wiring gaps before launch."},
        ],
    )

    _write_json(
        data_dir / "commit-eras.json",
        {
            "project": "Demo Archaeology",
            "lifespan": "5 days (2026-01-01 to 2026-01-05)",
            "total_commits": 6,
            "eras": [
                {"id": 1, "name": "Intent", "dates": "2026-01-01", "commits": 1, "description": "The project goal is written down.", "narrative_arc": "A clear intent appears before code."},
                {"id": 2, "name": "Prototype", "dates": "2026-01-01 to 2026-01-02", "commits": 2, "description": "The prototype is scaffolded and wired.", "narrative_arc": "Implementation pressure exposes the first integration gap."},
                {"id": 3, "name": "Hardening", "dates": "2026-01-03 to 2026-01-05", "commits": 3, "description": "Tests and audit boundaries are added.", "narrative_arc": "The project shifts from making claims to proving them."},
            ],
        },
    )

    _write_json(
        deliverables_dir / "canonical-metrics.json",
        {
            "generated": "2026-01-05",
            "source_scope": "sanitized demo fixture",
            "total_commits": 6,
            "span_days": 5,
            "active_days": 4,
            "peak_day": "2026-01-05",
            "peak_day_commits": 2,
            "session_count": 2,
            "human_messages": 2,
        },
    )

    (project_root / "README.md").write_text(
        "# Demo Archaeology\n\nThis is a sanitized demo fixture generated by `archaeology demo`. It contains invented data only.\n",
        encoding="utf-8",
    )
    (project_root / "PRIVACY-MANIFEST.md").write_text(
        "# Demo Privacy Manifest\n\nThis demo contains invented, sanitized fixture data only. It is safe to publish and contains no raw private sessions, behavioral exports, resumes, or personal telemetry.\n",
        encoding="utf-8",
    )
    return project_root
